name: Auto Commit to Branch

on:
  schedule:
    # run at 16:00 (UTC) every day
    - cron: "0 16 * * *"
  workflow_dispatch: # manual trigger

permissions:
  contents: write # 关键：允许 commit/push

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main.py
        run: |
          python src/main.py

      - name: Check output file
        run: |
          if [ ! -f output/rp_version.json ]; then
            echo "Error: output/rp_version.json not found!"
            exit 1
          fi
          if [ ! -f output/mcv.txt ]; then
            echo "Error: output/mcv.txt not found!"
            exit 1
          fi

      - name: Get datetime
        id: get-time
        run: |
          UTC_DATETIME=$(date -u +"%Y%m%dT%H%M%SZ")
          echo "time=$UTC_DATETIME" >> $GITHUB_OUTPUT

      - name: Copy *.json from output/ to root
        run: |
          cp -v output/*.json ./

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.get-time.outputs.time }}
          branch: main
          file_pattern: "*.json"
          add_options: "-A"
